      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

spring:
  application:
    name: api-gateway

  ignoredServices: '*'
  routes:
    demo-service:
      path: /demo/**
      service-id: demo-service


