eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8080

spring:
  application:
    name: api-gateway

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    a-service:
      path: /a/**
      service-id: a-service
    b-service:
      path: /b/**
      service-id: b-service


