server:
  port: 8080


spring:
  application:
    name: api-gateway

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    demo-service:
      path: /demo/**
      url: http://localhost:8081

    x-service:
      path: /x/**
      url: https://706c0671d145.ngrok.io/




