eureka:
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

spring:
  application:
    name: api-gateway

zuul:
  ignoredServices: '*'
  routes:
    demo-service:
      path: /demo/**
      service-id: demo-service


